### ISSUE TITLE
iPhone 5 wrong orientation

### ISSUE THREAD

**Issue by alexcroox** [Eccenux/WebCompass#1]
I ran your test page on my iPhone 5 and the correct North was showing as East on your compass and the correct West was showing as North.

**Comment by Eccenux** [comment]
Hi. Unfortunately I don't have access to iPhone 5 currently. You can try building a PhoneGap app on iOS. It worked fine when I tested on iPhone 3GS.

It's also possible that something weird happend when you rotated the device. If the browser switch from portrait to vertical then everything got mixed up. I don't know of any workaround for that in Safari. In PhoneGap you can lock rotation and that should help.

Please let me know if you managed to find a fix on your own or have additional information on the issue. Maybe you could debug with weinre?
http://people.apache.org/~pmuellr/weinre-docs/latest/Installing.html

**Comment by Eccenux** [comment]
Was not able to confirm this on latest iOS.

Maybe the problem was orientation changing? If so, and if you are using Cordova/PhoneGap you might need screen orientation lock: https://github.com/apache/cordova-plugin-screen-orientation
